name: Manual DNS Terraform Action

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action (apply/destroy/plan)'
        required: true
        default: 'plan'

jobs:
  manual-terraform-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd terraform/dns
        terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: |
        cd terraform/dns
        TF_LOG=DEBUG terraform destroy -auto-approve \
        -var="domain_name=${{ secrets.DOMAIN_NAME }}"
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add terraform.tfstate *.tf
        git commit -m "terraform files"
        git push || true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        
    - name: Terraform Plan
      if: github.event.inputs.action == 'apply' || github.event.inputs.action == 'plan'
      run: |
        cd terraform/dns
        TF_LOG=DEBUG terraform plan \
        -var="domain_name=${{ secrets.DOMAIN_NAME }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: |
        cd terraform/dns
        terraform apply -auto-approve \
        -var="domain_name=${{ secrets.DOMAIN_NAME }}"
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add *.tfstate *.tf
        git commit -m "terraform files"
        git push || true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
